export interface User {
  userId: number;
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  password?: string;
  roleId: number;
  gender: Gender;
  birthDate: string;
  phoneNumber: string;
  isActive: boolean;
  createdAt?: string;
  updatedAt?: string;
  role?: Role;
}

export interface Role {
  id: number;
  name: string;
  permissions: Permission[];
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER'
}

export enum Permission {
  CREATE_ROLE = 'CREATE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',
  READ_ROLE = 'READ_ROLE',
  CREATE_ADMINISTRATOR = 'CREATE_ADMINISTRATOR',
  UPDATE_ADMINISTRATOR = 'UPDATE_ADMINISTRATOR',
  DELETE_ADMINISTRATOR = 'DELETE_ADMINISTRATOR',
  READ_ADMINISTRATOR = 'READ_ADMINISTRATOR',
  CREATE_ADMIN = 'CREATE_ADMIN',
  UPDATE_ADMIN = 'UPDATE_ADMIN',
  DELETE_ADMIN = 'DELETE_ADMIN',
  READ_ADMIN = 'READ_ADMIN',
  CREATE_MANAGER = 'CREATE_MANAGER',
  UPDATE_MANAGER = 'UPDATE_MANAGER',
  DELETE_MANAGER = 'DELETE_MANAGER',
  READ_MANAGER = 'READ_MANAGER',
  CREATE_OPERATOR = 'CREATE_OPERATOR',
  UPDATE_OPERATOR = 'UPDATE_OPERATOR',
  DELETE_OPERATOR = 'DELETE_OPERATOR',
  READ_OPERATOR = 'READ_OPERATOR',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  READ_USER = 'READ_USER',
  CREATE_CAMP = 'CREATE_CAMP',
  UPDATE_CAMP = 'UPDATE_CAMP',
  DELETE_CAMP = 'DELETE_CAMP',
  READ_CAMP = 'READ_CAMP',
  CREATE_SANATARIUM = 'CREATE_SANATARIUM',
  UPDATE_SANATARIUM = 'UPDATE_SANATARIUM',
  DELETE_SANATARIUM = 'DELETE_SANATARIUM',
  READ_SANATARIUM = 'READ_SANATARIUM',
  CREATE_BOOKING = 'CREATE_BOOKING',
  UPDATE_BOOKING = 'UPDATE_BOOKING',
  DELETE_BOOKING = 'DELETE_BOOKING',
  READ_BOOKING = 'READ_BOOKING',
  CREATE_DOCUMENT = 'CREATE_DOCUMENT',
  UPDATE_DOCUMENT = 'UPDATE_DOCUMENT',
  DELETE_DOCUMENT = 'DELETE_DOCUMENT',
  READ_DOCUMENT = 'READ_DOCUMENT'
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  OPERATOR = 'OPERATOR',
  USER = 'USER'
}